CREATE TABLE stg1_Area_Conocimiento (
    ID_AREA_CONOCIMIENTO INT,
    NOMBRE_AREA_CONOCIMIENTO VARCHAR(255)
);


CREATE TABLE Area_Conocimiento (
    ID_A_CONOCIMIENTO INT PRIMARY KEY ,
    NOMBRE_AREA_CONOCIMIENTO VARCHAR(255)
);

CREATE TABLE STG1_Modalidad (
    ID_MODALIDAD INT ,
    NOMBRE_MODALIDAD VARCHAR(30)
);

CREATE TABLE Modalidad (
    ID_MODALIDAD INT PRIMARY KEY ,
    NOMBRE_MODALIDAD VARCHAR(30)
);


CREATE TABLE Stg1_Departamento (
    ID_DEPARTAMENTO INT,
    NOMBRE_DEPARTAMENTO VARCHAR(255)
);

CREATE TABLE Departamento (
    ID_DEPARTAMENTO INT PRIMARY KEY ,
    NOMBRE_DEPARTAMENTO VARCHAR(255)
);




CREATE TABLE stg1_Municipio (
    ID_MUNICIPIO INT ,
    NOMBRE_MUNICIPIO VARCHAR(255)
);

CREATE TABLE Municipio (
    ID_MUNICIPIO INT PRIMARY KEY ,
    NOMBRE_MUNICIPIO VARCHAR(255)
);

CREATE TABLE stg1_Nivel_Academico (
    id_nvl_academico INT,
    NOMBRE_NIVEL_ACADEMICO VARCHAR(50)
);

CREATE TABLE Nivel_Academico (
    ID_NVL_ACADEMICO INT PRIMARY KEY,
    NOMBRE_NIVEL_ACADEMICO VARCHAR(50)
);


CREATE TABLE stg1_Institucion (
    ID_INSTITUCION INT,
    NOMBRE_INSTITUCION VARCHAR(255),
    CARACTER_IES VARCHAR(255),
    IES_ACREDITADA varchar(2),
    CÓDIGO_DEL_DEPARTAMENTO INT,
    DEPARTAMENTO_IES VARCHAR(255)
);

CREATE TABLE stg2_Institucion (
    ID_INSTITUCION INT PRIMARY KEY ,
    NOMBRE_INSTITUCION VARCHAR(255),
    CARACTER_IES VARCHAR(255),
    IES_ACREDITADA varchar(2),
    CÓDIGO_DEL_DEPARTAMENTO INT,
    DEPARTAMENTO_IES VARCHAR(255)
);


CREATE TABLE Institucion (
    ID_INS INT PRIMARY KEY ,
    NOMBRE_INSTITUCION VARCHAR(255),
    CARACTER_IES VARCHAR(255),
    IES_ACREDITADA varchar(2),
    CÓDIGO_DEL_DEPARTAMENTO INT,
    FOREIGN KEY (CÓDIGO_DEL_DEPARTAMENTO) REFERENCES Departamento(ID_DEPARTAMENTO)
);




CREATE TABLE stage (
    CODIGO_INSTITUCION INT,
    NOMBRE_INSTITUCION VARCHAR(255),
    CARACTER_IES VARCHAR(255),
    CODIGO_DEPARTAMENTO_IES INT,
    DEPARTAMENTO_DOMICILIO_IES VARCHAR(255),
    IES_ACREDITADA varchar(2),
    CODIGO_SNIES_PROGRAMA INT,
    PROGRAMA_ACADEMICO VARCHAR(255),
    PROGRAMA_ACREDITADO varchar(2),
    ID_NIVEL_ACADEMICO INT,
    NIVEL_ACADEMICO VARCHAR(255),
    NIVEL_FORMACION VARCHAR(255),
    ID_NIVEL_FORMACION INT,
    ID_MODALIDAD INT,
    MODALIDAD VARCHAR(50),
    ID_AREA_CONOCIMIENTO INT,
    AREA_CONOCIMIENTO VARCHAR(255),
    CODIGO_DEPARTAMENTO_PROGRAMA INT,
    DEPARTAMENTO_OFERTA_PROGRAMA VARCHAR(255),
    CODIGO_MUNICIPIO_PROGRAMA INT,
    MUNICIPIO_OFERTA_PROGRAMA VARCHAR(255),
    ID_SEXO INT,
    SEXO VARCHAR(10),
    ANO INT,
    SEMESTRE INT,
    GRADUADOS INT
);


CREATE TABLE stg1_Graduados (
    CODIGO_INSTITUCION INT,
    NOMBRE_INSTITUCION VARCHAR(255),
    CARACTER_IES VARCHAR(255),
    CODIGO_DEPARTAMENTO_IES INT,
    DEPARTAMENTO_DOMICILIO_IES VARCHAR(255),
    CODIGO_SNIES_PROGRAMA INT,
    PROGRAMA_ACADEMICO VARCHAR(255),
    ID_NIVEL_ACADEMICO INT,
    NIVEL_ACADEMICO VARCHAR(255),
    ID_AREA_CONOCIMIENTO INT,
    AREA_CONOCIMIENTO VARCHAR(255),
    CODIGO_DEPARTAMENTO_PROGRAMA INT,
    DEPARTAMENTO_OFERTA_PROGRAMA VARCHAR(255),
    CODIGO_MUNICIPIO_PROGRAMA INT,
    MUNICIPIO_OFERTA_PROGRAMA VARCHAR(255),
    graduados_masculinos INT,
    graduados_femeninos int ,
    graduados int
);

CREATE TABLE stg2_Graduados (
    CODIGO_INSTITUCION INT,
    CARACTER_IES VARCHAR(255),
    CODIGO_SNIES_PROGRAMA INT,
    PROGRAMA_ACADEMICO VARCHAR(255),
    ID_NIVEL_ACADEMICO INT,
    NIVEL_ACADEMICO VARCHAR(255),
    ID_AREA_CONOCIMIENTO INT,
    AREA_CONOCIMIENTO VARCHAR(255),
    CODIGO_DEPARTAMENTO_PROGRAMA INT,
    DEPARTAMENTO_OFERTA_PROGRAMA VARCHAR(255),
    CODIGO_MUNICIPIO_PROGRAMA INT,
    MUNICIPIO_OFERTA_PROGRAMA VARCHAR(255),
    graduados_masculinos INT,
    graduados_femeninos int ,
    graduados int,
    FOREIGN KEY (CODIGO_INSTITUCION) REFERENCES Institucion(id_ins)
);

CREATE TABLE stg3_Graduados (
    CODIGO_INSTITUCION INT,
    CODIGO_PROGRAMA INT,
    PROGRAMA_ACADEMICO VARCHAR(255),
    ID_NIVEL_ACADEMICO INT,
    ID_AREA_CONOCIMIENTO INT,
    AREA_CONOCIMIENTO VARCHAR(255),
    CODIGO_DEPARTAMENTO_PROGRAMA INT,
    DEPARTAMENTO_OFERTA_PROGRAMA VARCHAR(255),
    CODIGO_MUNICIPIO_PROGRAMA INT,
    MUNICIPIO_OFERTA_PROGRAMA VARCHAR(255),
    graduados_masculinos INT,
    graduados_femeninos int ,
    graduados int,
    FOREIGN KEY (CODIGO_INSTITUCION) REFERENCES Institucion(id_ins),
    FOREIGN KEY (ID_NIVEL_ACADEMICO) REFERENCES nivel_academico(id_nivel_academico)
);


CREATE TABLE stg4_Graduados (
    CODIGO_INSTITUCION INT,
    CODIGO_PROGRAMA INT,
    PROGRAMA_ACADEMICO VARCHAR(255),
    ID_NIVEL_ACADEMICO INT,
    ID_AREA_CONOCIMIENTO INT,
    CODIGO_DEPARTAMENTO_PROGRAMA INT,
    DEPARTAMENTO_OFERTA_PROGRAMA VARCHAR(255),
    CODIGO_MUNICIPIO_PROGRAMA INT,
    MUNICIPIO_OFERTA_PROGRAMA VARCHAR(255),
    graduados_masculinos INT,
    graduados_femeninos int ,
    graduados int,
    FOREIGN KEY (CODIGO_INSTITUCION) REFERENCES Institucion(id_ins),
    FOREIGN KEY (ID_NIVEL_ACADEMICO) REFERENCES nivel_academico(id_nvl_academico),
    FOREIGN KEY (ID_AREA_CONOCIMIENTO) REFERENCES Area_Conocimiento(ID_A_CONOCIMIENTO)
);


CREATE TABLE Graduados (
    CODIGO_INSTITUCION INT,
    CODIGO_PROGRAMA INT,
    PROGRAMA_ACADEMICO VARCHAR(255),
    ID_NIVEL_ACADEMICO INT,
    ID_AREA_CONOCIMIENTO INT,
    CODIGO_DEPARTAMENTO_PROGRAMA INT,
    CODIGO_MUNICIPIO_PROGRAMA INT,
    graduados_masculinos INT,
    graduados_femeninos int ,
    graduados int,
    FOREIGN KEY (CODIGO_INSTITUCION) REFERENCES Institucion(id_ins),
    FOREIGN KEY (ID_NIVEL_ACADEMICO) REFERENCES nivel_academico(id_nvl_academico),
    FOREIGN KEY (ID_AREA_CONOCIMIENTO) REFERENCES Area_Conocimiento(ID_A_CONOCIMIENTO),
    FOREIGN KEY (CODIGO_DEPARTAMENTO_PROGRAMA) REFERENCES departamento(ID_DEPARTAMENTO),
    FOREIGN KEY (CODIGO_MUNICIPIO_PROGRAMA) REFERENCES municipio(ID_MUNICIPIO)
);

ALTER TABLE graduados
ADD COLUMN id_registro SERIAL PRIMARY KEY;
